server:
  port: 8081

spring:
  application:
    name: harvest
  profiles:
    group:
      wiki-dump-test: test, wiki-dump
  output:
    ansi:
      enabled: always
  batch:
    # Spring Batch 메타데이터 테이블 자동 생성
    jdbc:
      initialize-schema: always
    job:
      # 애플리케이션 시작 시 자동으로 Job 실행 여부
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/harvest_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: realtime
    password: realtime1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
harvest:
  description: "대용량 파일 수집 시스템 - 수확기"
  version: 1.0.0

# 배치 관련 설정
batch:
  chunk:
    size: 100
  wiki:
    file:
      path: file:${user.home}/bigdata/kowiki-20250901-pages-articles-multistream1.xml-p1p82407.bz2

# 로깅 설정
logging:
  level:
    com.sandro.realtime.harvest: DEBUG
    org.springframework.batch: INFO
    org.springframework.batch.core.job: DEBUG
    org.springframework.batch.core.step: DEBUG