name: Pull Request CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: ./gradlew build

      # 테스트 실패 시 테스트 리포트 업로드
      - name: Upload report files
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            harvest/build/reports/tests/test/
